[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build", "sh ./node_modules/.bin/prisma generate"]

[start]
cmd = "sh ./node_modules/.bin/prisma db push --accept-data-loss && node dist/index.js"
